# Use the official PostgreSQL 12 image as a base
FROM postgres:16-alpine

# Set the default command for the container, this is optional since the base image already has an entrypoint
CMD ["postgres"]
