-- Seed English questions
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-simple', 'irregular', 'auxiliary', 'She ______ a doctor at the local hospital.', 'She is a doctor at the local hospital.', '[{"id": "a1", "text": "is", "isCorrect": true}, {"id": "a2", "text": "are", "isCorrect": false}, {"id": "a3", "text": "am", "isCorrect": false}, {"id": "a4", "text": "be", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-simple', 'irregular', 'irregular', 'They ______ a big house in the countryside.', 'They have a big house in the countryside.', '[{"id": "a1", "text": "have", "isCorrect": true}, {"id": "a2", "text": "has", "isCorrect": false}, {"id": "a3", "text": "had", "isCorrect": false}, {"id": "a4", "text": "having", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-simple', 'irregular', 'irregular', 'He ______ to work by bus every morning.', 'He goes to work by bus every morning.', '[{"id": "a1", "text": "goes", "isCorrect": true}, {"id": "a2", "text": "go", "isCorrect": false}, {"id": "a3", "text": "went", "isCorrect": false}, {"id": "a4", "text": "going", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-simple', 'regular', 'regular', 'I ______ French and a little Italian.', 'I speak French and a little Italian.', '[{"id": "a1", "text": "speak", "isCorrect": true}, {"id": "a2", "text": "speaks", "isCorrect": false}, {"id": "a3", "text": "spoke", "isCorrect": false}, {"id": "a4", "text": "spoken", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-simple', 'irregular', 'irregular', 'We ______ dinner together at seven every evening.', 'We eat dinner together at seven every evening.', '[{"id": "a1", "text": "eat", "isCorrect": true}, {"id": "a2", "text": "eats", "isCorrect": false}, {"id": "a3", "text": "ate", "isCorrect": false}, {"id": "a4", "text": "eaten", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-simple', 'regular', 'regular', 'They ______ in New York near Central Park.', 'They live in New York near Central Park.', '[{"id": "a1", "text": "live", "isCorrect": true}, {"id": "a2", "text": "lives", "isCorrect": false}, {"id": "a3", "text": "lived", "isCorrect": false}, {"id": "a4", "text": "living", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-simple', 'irregular', 'irregular', 'What ______ you do for work?', 'What do you do for work?', '[{"id": "a1", "text": "do", "isCorrect": true}, {"id": "a2", "text": "does", "isCorrect": false}, {"id": "a3", "text": "did", "isCorrect": false}, {"id": "a4", "text": "doing", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-simple', 'irregular', 'auxiliary', 'I ______ very tired after the long hike yesterday.', 'I was very tired after the long hike yesterday.', '[{"id": "a1", "text": "was", "isCorrect": true}, {"id": "a2", "text": "were", "isCorrect": false}, {"id": "a3", "text": "am", "isCorrect": false}, {"id": "a4", "text": "been", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-simple', 'irregular', 'irregular', 'She ______ to the store to buy some groceries.', 'She went to the store to buy some groceries.', '[{"id": "a1", "text": "went", "isCorrect": true}, {"id": "a2", "text": "go", "isCorrect": false}, {"id": "a3", "text": "gone", "isCorrect": false}, {"id": "a4", "text": "going", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-simple', 'irregular', 'irregular', 'They ______ lunch together at that new café.', 'They had lunch together at that new café.', '[{"id": "a1", "text": "had", "isCorrect": true}, {"id": "a2", "text": "have", "isCorrect": false}, {"id": "a3", "text": "has", "isCorrect": false}, {"id": "a4", "text": "having", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-simple', 'irregular', 'irregular', 'He ______ to the manager about the problem.', 'He spoke to the manager about the problem.', '[{"id": "a1", "text": "spoke", "isCorrect": true}, {"id": "a2", "text": "speak", "isCorrect": false}, {"id": "a3", "text": "speaking", "isCorrect": false}, {"id": "a4", "text": "spoken", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-simple', 'irregular', 'irregular', 'We ______ pizza together last Friday night.', 'We ate pizza together last Friday night.', '[{"id": "a1", "text": "ate", "isCorrect": true}, {"id": "a2", "text": "eat", "isCorrect": false}, {"id": "a3", "text": "eaten", "isCorrect": false}, {"id": "a4", "text": "eats", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-simple', 'regular', 'regular', 'She ______ in Paris for a whole year.', 'She lived in Paris for a whole year.', '[{"id": "a1", "text": "lived", "isCorrect": true}, {"id": "a2", "text": "live", "isCorrect": false}, {"id": "a3", "text": "living", "isCorrect": false}, {"id": "a4", "text": "lives", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-simple', 'irregular', 'irregular', 'What ______ you do at the weekend?', 'What did you do at the weekend?', '[{"id": "a1", "text": "did", "isCorrect": true}, {"id": "a2", "text": "do", "isCorrect": false}, {"id": "a3", "text": "does", "isCorrect": false}, {"id": "a4", "text": "done", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('future-simple', 'irregular', 'auxiliary', 'It ______ cold tomorrow according to the forecast.', 'It will be cold tomorrow according to the forecast.', '[{"id": "a1", "text": "will be", "isCorrect": true}, {"id": "a2", "text": "is", "isCorrect": false}, {"id": "a3", "text": "was", "isCorrect": false}, {"id": "a4", "text": "would be", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('future-simple', 'irregular', 'irregular', 'I ______ to Paris next year for the conference.', 'I will go to Paris next year for the conference.', '[{"id": "a1", "text": "will go", "isCorrect": true}, {"id": "a2", "text": "went", "isCorrect": false}, {"id": "a3", "text": "am going", "isCorrect": false}, {"id": "a4", "text": "would go", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('future-simple', 'regular', 'regular', 'She ______ at the international conference next month.', 'She will speak at the international conference next month.', '[{"id": "a1", "text": "will speak", "isCorrect": true}, {"id": "a2", "text": "spoke", "isCorrect": false}, {"id": "a3", "text": "speaks", "isCorrect": false}, {"id": "a4", "text": "would speak", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('future-simple', 'irregular', 'irregular', 'They ______ a party for your birthday.', 'They will have a party for your birthday.', '[{"id": "a1", "text": "will have", "isCorrect": true}, {"id": "a2", "text": "had", "isCorrect": false}, {"id": "a3", "text": "have", "isCorrect": false}, {"id": "a4", "text": "would have", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-continuous', 'irregular', 'irregular', 'They ______ a movie right now on the big screen.', 'They are watching a movie right now on the big screen.', '[{"id": "a1", "text": "are watching", "isCorrect": true}, {"id": "a2", "text": "watch", "isCorrect": false}, {"id": "a3", "text": "watched", "isCorrect": false}, {"id": "a4", "text": "will watch", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-continuous', 'irregular', 'irregular', 'She ______ to school right now with her friends.', 'She is going to school right now with her friends.', '[{"id": "a1", "text": "is going", "isCorrect": true}, {"id": "a2", "text": "goes", "isCorrect": false}, {"id": "a3", "text": "went", "isCorrect": false}, {"id": "a4", "text": "will go", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-continuous', 'regular', 'regular', 'He ______ on the phone. Please wait a moment.', 'He is speaking on the phone. Please wait a moment.', '[{"id": "a1", "text": "is speaking", "isCorrect": true}, {"id": "a2", "text": "speaks", "isCorrect": false}, {"id": "a3", "text": "spoke", "isCorrect": false}, {"id": "a4", "text": "will speak", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-continuous', 'regular', 'regular', 'We ______ in our new apartment this week.', 'We are living in our new apartment this week.', '[{"id": "a1", "text": "are living", "isCorrect": true}, {"id": "a2", "text": "live", "isCorrect": false}, {"id": "a3", "text": "lived", "isCorrect": false}, {"id": "a4", "text": "will live", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-continuous', 'irregular', 'auxiliary', 'We ______ TV when he suddenly called.', 'We were watching TV when he suddenly called.', '[{"id": "a1", "text": "were watching", "isCorrect": true}, {"id": "a2", "text": "watched", "isCorrect": false}, {"id": "a3", "text": "are watching", "isCorrect": false}, {"id": "a4", "text": "had watched", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-continuous', 'regular', 'regular', 'They ______ when I arrived at the meeting.', 'They were speaking when I arrived at the meeting.', '[{"id": "a1", "text": "were speaking", "isCorrect": true}, {"id": "a2", "text": "spoke", "isCorrect": false}, {"id": "a3", "text": "are speaking", "isCorrect": false}, {"id": "a4", "text": "had spoken", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-continuous', 'irregular', 'irregular', 'She ______ in London when the news broke.', 'She was living in London when the news broke.', '[{"id": "a1", "text": "was living", "isCorrect": true}, {"id": "a2", "text": "lived", "isCorrect": false}, {"id": "a3", "text": "is living", "isCorrect": false}, {"id": "a4", "text": "had lived", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-perfect', 'irregular', 'auxiliary', 'I ______ this book before. It is excellent.', 'I have read this book before. It is excellent.', '[{"id": "a1", "text": "have read", "isCorrect": true}, {"id": "a2", "text": "read", "isCorrect": false}, {"id": "a3", "text": "am reading", "isCorrect": false}, {"id": "a4", "text": "will read", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-perfect', 'irregular', 'irregular', 'She ______ to Japan twice in her life.', 'She has gone to Japan twice in her life.', '[{"id": "a1", "text": "has gone", "isCorrect": true}, {"id": "a2", "text": "went", "isCorrect": false}, {"id": "a3", "text": "has went", "isCorrect": false}, {"id": "a4", "text": "is going", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('present-perfect', 'irregular', 'irregular', 'They ______ many interesting people at the event.', 'They have met many interesting people at the event.', '[{"id": "a1", "text": "have met", "isCorrect": true}, {"id": "a2", "text": "met", "isCorrect": false}, {"id": "a3", "text": "have meet", "isCorrect": false}, {"id": "a4", "text": "are meeting", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-perfect', 'irregular', 'auxiliary', 'She ______ there many times before moving away.', 'She had been there many times before moving away.', '[{"id": "a1", "text": "had been", "isCorrect": true}, {"id": "a2", "text": "was", "isCorrect": false}, {"id": "a3", "text": "has been", "isCorrect": false}, {"id": "a4", "text": "would be", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-perfect', 'irregular', 'irregular', 'They ______ already when we got to the station.', 'They had gone already when we got to the station.', '[{"id": "a1", "text": "had gone", "isCorrect": true}, {"id": "a2", "text": "went", "isCorrect": false}, {"id": "a3", "text": "have gone", "isCorrect": false}, {"id": "a4", "text": "were going", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('past-perfect', 'irregular', 'irregular', 'He ______ his lunch by the time I arrived.', 'He had eaten his lunch by the time I arrived.', '[{"id": "a1", "text": "had eaten", "isCorrect": true}, {"id": "a2", "text": "ate", "isCorrect": false}, {"id": "a3", "text": "has eaten", "isCorrect": false}, {"id": "a4", "text": "was eating", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('conditional', 'irregular', 'auxiliary', 'I ______ very happy if I won the lottery.', 'I would be very happy if I won the lottery.', '[{"id": "a1", "text": "would be", "isCorrect": true}, {"id": "a2", "text": "will be", "isCorrect": false}, {"id": "a3", "text": "am", "isCorrect": false}, {"id": "a4", "text": "was", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('conditional', 'irregular', 'irregular', 'She ______ if she had enough money saved.', 'She would go if she had enough money saved.', '[{"id": "a1", "text": "would go", "isCorrect": true}, {"id": "a2", "text": "will go", "isCorrect": false}, {"id": "a3", "text": "went", "isCorrect": false}, {"id": "a4", "text": "goes", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('conditional', 'regular', 'regular', 'He ______ more clearly if he practiced more.', 'He would speak more clearly if he practiced more.', '[{"id": "a1", "text": "would speak", "isCorrect": true}, {"id": "a2", "text": "will speak", "isCorrect": false}, {"id": "a3", "text": "speaks", "isCorrect": false}, {"id": "a4", "text": "spoke", "isCorrect": false}]', 'easy', 'english');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('conditional', 'irregular', 'irregular', 'They ______ more if they understood the benefits.', 'They would eat more if they understood the benefits.', '[{"id": "a1", "text": "would eat", "isCorrect": true}, {"id": "a2", "text": "will eat", "isCorrect": false}, {"id": "a3", "text": "ate", "isCorrect": false}, {"id": "a4", "text": "eat", "isCorrect": false}]', 'easy', 'english');
