-- Seed Portuguese questions from old/questions.json
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'regular', 'er', 'Eu ______ café todas as manhãs.', 'I drink coffee every morning.', '[{"id": "a1", "text": "bebo", "isCorrect": true}, {"id": "a2", "text": "bebe", "isCorrect": false}, {"id": "a3", "text": "bebemos", "isCorrect": false}, {"id": "a4", "text": "bebem", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'irregular', 'ar', 'Eles ______ ontem.', 'They played yesterday.', '[{"id": "a1", "text": "jogaram", "isCorrect": true}, {"id": "a2", "text": "jogavam", "isCorrect": false}, {"id": "a3", "text": "jogarão", "isCorrect": false}, {"id": "a4", "text": "joguem", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro-do-presente', 'regular', 'ir', 'Você ______ no jogo?', 'Will you participate in the game?', '[{"id": "a1", "text": "participará", "isCorrect": true}, {"id": "a2", "text": "participa", "isCorrect": false}, {"id": "a3", "text": "participava", "isCorrect": false}, {"id": "a4", "text": "participou", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-imperfeito', 'regular', 'ar', 'Nós ______ quando éramos crianças.', 'We played when we were children.', '[{"id": "a1", "text": "jogávamos", "isCorrect": true}, {"id": "a2", "text": "jogamos", "isCorrect": false}, {"id": "a3", "text": "jogaríamos", "isCorrect": false}, {"id": "a4", "text": "jogaremos", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'irregular', 'er', 'Ela ______ bem.', 'She reads well.', '[{"id": "a1", "text": "lê", "isCorrect": true}, {"id": "a2", "text": "leu", "isCorrect": false}, {"id": "a3", "text": "lerá", "isCorrect": false}, {"id": "a4", "text": "lia", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-mais-que-perfeito', 'regular', 'ar', 'Nós já ______ a prova.', 'We had already taken the exam.', '[{"id": "a1", "text": "fizéramos", "isCorrect": true}, {"id": "a2", "text": "fazemos", "isCorrect": false}, {"id": "a3", "text": "faremos", "isCorrect": false}, {"id": "a4", "text": "fazíamos", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'regular', 'er', 'Eles ______ a verdade.', 'They know the truth.', '[{"id": "a1", "text": "sabem", "isCorrect": true}, {"id": "a2", "text": "saberão", "isCorrect": false}, {"id": "a3", "text": "sabiam", "isCorrect": false}, {"id": "a4", "text": "souberam", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro-do-presente', 'irregular', 'ir', 'Ele ______ de avião.', 'He will come by plane.', '[{"id": "a1", "text": "virá", "isCorrect": true}, {"id": "a2", "text": "vem", "isCorrect": false}, {"id": "a3", "text": "veio", "isCorrect": false}, {"id": "a4", "text": "vinha", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'ar', 'Você _______ a lição?', 'Did you complete the lesson?', '[{"id": "a1", "text": "completou", "isCorrect": true}, {"id": "a2", "text": "completa", "isCorrect": false}, {"id": "a3", "text": "completava", "isCorrect": false}, {"id": "a4", "text": "completará", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-imperfeito', 'regular', 'er', 'Eu não ______ o que fazer.', 'I did not know what to do.', '[{"id": "a1", "text": "sabia", "isCorrect": true}, {"id": "a2", "text": "sei", "isCorrect": false}, {"id": "a3", "text": "saberei", "isCorrect": false}, {"id": "a4", "text": "soube", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'regular', 'ir', 'Nós ______ a verdade.', 'We open the door.', '[{"id": "a1", "text": "abrimos", "isCorrect": true}, {"id": "a2", "text": "abrirá", "isCorrect": false}, {"id": "a3", "text": "abria", "isCorrect": false}, {"id": "a4", "text": "abriu", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro-do-presente', 'regular', 'er', 'Ela ______ o livro.', 'She will read the book.', '[{"id": "a1", "text": "lerá", "isCorrect": true}, {"id": "a2", "text": "lê", "isCorrect": false}, {"id": "a3", "text": "lia", "isCorrect": false}, {"id": "a4", "text": "leu", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'irregular', 'er', 'Nós ______ a resposta.', 'We had the answer.', '[{"id": "a1", "text": "tivemos", "isCorrect": true}, {"id": "a2", "text": "temos", "isCorrect": false}, {"id": "a3", "text": "teremos", "isCorrect": false}, {"id": "a4", "text": "tínhamos", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-imperfeito', 'regular', 'ar', 'Ela _______ bem.', 'She used to sing well.', '[{"id": "a1", "text": "cantava", "isCorrect": true}, {"id": "a2", "text": "canta", "isCorrect": false}, {"id": "a3", "text": "cantará", "isCorrect": false}, {"id": "a4", "text": "cantou", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'irregular', 'ir', 'Eles ______ para a escola.', 'They go to school.', '[{"id": "a1", "text": "vão", "isCorrect": true}, {"id": "a2", "text": "vem", "isCorrect": false}, {"id": "a3", "text": "virão", "isCorrect": false}, {"id": "a4", "text": "vieram", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro-do-presente', 'regular', 'ar', 'Você ______ o carro?', 'Will you wash the car?', '[{"id": "a1", "text": "lavará", "isCorrect": true}, {"id": "a2", "text": "lava", "isCorrect": false}, {"id": "a3", "text": "lavava", "isCorrect": false}, {"id": "a4", "text": "lavou", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'ir', 'Nós ________ a cidade.', 'We visited the city.', '[{"id": "a1", "text": "visitamos", "isCorrect": true}, {"id": "a2", "text": "visitávamos", "isCorrect": false}, {"id": "a3", "text": "visitaremos", "isCorrect": false}, {"id": "a4", "text": "visitaríamos", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-imperfeito', 'irregular', 'er', 'Eu _______ sempre àquela loja.', 'I used to go to that store.', '[{"id": "a1", "text": "ia", "isCorrect": true}, {"id": "a2", "text": "vou", "isCorrect": false}, {"id": "a3", "text": "irei", "isCorrect": false}, {"id": "a4", "text": "fui", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'regular', 'er', 'Eles ________ música.', 'They hear music.', '[{"id": "a1", "text": "ouvem", "isCorrect": true}, {"id": "a2", "text": "ouviu", "isCorrect": false}, {"id": "a3", "text": "ouvirão", "isCorrect": false}, {"id": "a4", "text": "ouviam", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro-do-presente', 'irregular', 'ar', 'Eu ______ você amanhã.', 'I will call you tomorrow.', '[{"id": "a1", "text": "ligarei", "isCorrect": true}, {"id": "a2", "text": "ligo", "isCorrect": false}, {"id": "a3", "text": "ligava", "isCorrect": false}, {"id": "a4", "text": "liguei", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente-progressivo', 'regular', 'ar', 'Eu ________ o texto agora.', 'I am reading the text now.', '[{"id": "a1", "text": "estou lendo", "isCorrect": true}, {"id": "a2", "text": "li", "isCorrect": false}, {"id": "a3", "text": "leria", "isCorrect": false}, {"id": "a4", "text": "leio", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro-do-preterito', 'regular', 'er', 'Você ________ se soubesse.', 'You would eat if you knew.', '[{"id": "a1", "text": "comeria", "isCorrect": true}, {"id": "a2", "text": "come", "isCorrect": false}, {"id": "a3", "text": "comem", "isCorrect": false}, {"id": "a4", "text": "comia", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'irregular', 'ir', 'Ele ________ muito bem.', 'He feels very well.', '[{"id": "a1", "text": "sente", "isCorrect": true}, {"id": "a2", "text": "sentiria", "isCorrect": false}, {"id": "a3", "text": "sentiu", "isCorrect": false}, {"id": "a4", "text": "sentir", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'ar', 'Nós ________ a verdade.', 'We discovered the truth.', '[{"id": "a1", "text": "descobrimos", "isCorrect": true}, {"id": "a2", "text": "descobriríamos", "isCorrect": false}, {"id": "a3", "text": "descobríamos", "isCorrect": false}, {"id": "a4", "text": "descobremos", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro-do-presente', 'regular', 'ir', 'Ela ________ a resposta em breve.', 'She will choose the answer soon.', '[{"id": "a1", "text": "escolherá", "isCorrect": true}, {"id": "a2", "text": "escolheu", "isCorrect": false}, {"id": "a3", "text": "escolhia", "isCorrect": false}, {"id": "a4", "text": "escolhe", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente-progressivo', 'regular', 'er', 'Nós ________ para a festa.', 'We are running to the party.', '[{"id": "a1", "text": "estamos correndo", "isCorrect": true}, {"id": "a2", "text": "corremos", "isCorrect": false}, {"id": "a3", "text": "correríamos", "isCorrect": false}, {"id": "a4", "text": "corri", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro-do-preterito', 'irregular', 'ir', 'Eles ________ se pudessem.', 'They would go if they could.', '[{"id": "a1", "text": "iriam", "isCorrect": true}, {"id": "a2", "text": "foram", "isCorrect": false}, {"id": "a3", "text": "vão", "isCorrect": false}, {"id": "a4", "text": "indo", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'regular', 'ar', 'Você ________ muito bem.', 'You dance very well.', '[{"id": "a1", "text": "dança", "isCorrect": true}, {"id": "a2", "text": "dançaria", "isCorrect": false}, {"id": "a3", "text": "dançou", "isCorrect": false}, {"id": "a4", "text": "dançavam", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'er', 'Eu ________ o contrato.', 'I read the contract.', '[{"id": "a1", "text": "li", "isCorrect": true}, {"id": "a2", "text": "leria", "isCorrect": false}, {"id": "a3", "text": "lê", "isCorrect": false}, {"id": "a4", "text": "lendo", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente-progressivo', 'irregular', 'ir', 'Eles ________.', 'They are coming.', '[{"id": "a1", "text": "estão vindo", "isCorrect": true}, {"id": "a2", "text": "vêm", "isCorrect": false}, {"id": "a3", "text": "viriam", "isCorrect": false}, {"id": "a4", "text": "vieram", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro-do-presente', 'regular', 'ar', 'Eles ________ o jogo.', 'They will win the game.', '[{"id": "a1", "text": "ganharão", "isCorrect": true}, {"id": "a2", "text": "ganham", "isCorrect": false}, {"id": "a3", "text": "ganhar", "isCorrect": false}, {"id": "a4", "text": "ganhasse", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'regular', 'er', 'Eu ________ bem.', 'I understand well.', '[{"id": "a1", "text": "entendo", "isCorrect": true}, {"id": "a2", "text": "entenderei", "isCorrect": false}, {"id": "a3", "text": "entendia", "isCorrect": false}, {"id": "a4", "text": "entenderia", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'irregular', 'ir', 'Você ________ o carro.', 'You had the car.', '[{"id": "a1", "text": "teve", "isCorrect": true}, {"id": "a2", "text": "teria", "isCorrect": false}, {"id": "a3", "text": "tem", "isCorrect": false}, {"id": "a4", "text": "tinha", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente-progressivo', 'regular', 'ar', 'Nós ________ cantando.', 'We are singing.', '[{"id": "a1", "text": "estamos", "isCorrect": true}, {"id": "a2", "text": "éramos", "isCorrect": false}, {"id": "a3", "text": "seríamos", "isCorrect": false}, {"id": "a4", "text": "somos", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro-do-preterito', 'irregular', 'ir', 'Eu ________ a verdade.', 'I would say the truth.', '[{"id": "a1", "text": "diria", "isCorrect": true}, {"id": "a2", "text": "diz", "isCorrect": false}, {"id": "a3", "text": "disse", "isCorrect": false}, {"id": "a4", "text": "dizer", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'irregular', 'ir', 'Nós ___ ao museu na semana passada.', 'We went to the museum last week.', '[{"id": "a1", "text": "fomos", "isCorrect": true}, {"id": "a2", "text": "vai", "isCorrect": false}, {"id": "a3", "text": "vamos", "isCorrect": false}, {"id": "a4", "text": "ia", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'encontrar', 'Eu ___ um livro interessante.', 'I found an interesting book.', '[{"id": "a1", "text": "encontro", "isCorrect": false}, {"id": "a2", "text": "encontras", "isCorrect": false}, {"id": "a3", "text": "encontrei", "isCorrect": true}, {"id": "a4", "text": "encontramos", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'caminhar', 'Ele ___ pela rua quando a viu.', 'He walked down the street when he saw her.', '[{"id": "a1", "text": "caminhou", "isCorrect": true}, {"id": "a2", "text": "correu", "isCorrect": false}, {"id": "a3", "text": "voou", "isCorrect": false}, {"id": "a4", "text": "navegou", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'irregular', 'ir', 'Nós ___ ao museu na semana passada.', 'We went to the museum last week.', '[{"id": "a1", "text": "fomos", "isCorrect": true}, {"id": "a2", "text": "vai", "isCorrect": false}, {"id": "a3", "text": "vamos", "isCorrect": false}, {"id": "a4", "text": "ia", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'encontrar', 'Eu ___ um livro interessante.', 'I found an interesting book.', '[{"id": "a1", "text": "encontro", "isCorrect": false}, {"id": "a2", "text": "encontras", "isCorrect": false}, {"id": "a3", "text": "encontrei", "isCorrect": true}, {"id": "a4", "text": "encontramos", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'caminhar', 'Ele ___ pela rua quando a viu.', 'He walked down the street when he saw her.', '[{"id": "a1", "text": "caminhou", "isCorrect": true}, {"id": "a2", "text": "correu", "isCorrect": false}, {"id": "a3", "text": "voou", "isCorrect": false}, {"id": "a4", "text": "navegou", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'irregular', 'ver', 'Elas ___ o show inteiro.', 'They watched the whole show.', '[{"id": "a1", "text": "observaram", "isCorrect": false}, {"id": "a2", "text": "viram", "isCorrect": true}, {"id": "a3", "text": "ouviram", "isCorrect": false}, {"id": "a4", "text": "sentiram", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'lavar', 'Nós ___ o carro porque estava sujo.', 'We washed the car because it was dirty.', '[{"id": "a1", "text": "lavámos", "isCorrect": true}, {"id": "a2", "text": "secamos", "isCorrect": false}, {"id": "a3", "text": "dirigimos", "isCorrect": false}, {"id": "a4", "text": "pintamos", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'completar', 'Ele ___ a tarefa em duas horas.', 'He finished the task in two hours.', '[{"id": "a1", "text": "completou", "isCorrect": true}, {"id": "a2", "text": "começou", "isCorrect": false}, {"id": "a3", "text": "prolongou", "isCorrect": false}, {"id": "a4", "text": "atrasou", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'encontrar', 'Eu ___ meu irmão na estação.', 'I met my brother at the station.', '[{"id": "a1", "text": "encontrei", "isCorrect": true}, {"id": "a2", "text": "perdi", "isCorrect": false}, {"id": "a3", "text": "evitei", "isCorrect": false}, {"id": "a4", "text": "esqueci", "isCorrect": false}]', 'easy', 'portuguese');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfeito', 'regular', 'abrir', 'Ela ___ a janela para entrar ar.', 'She opened the window to let in some air.', '[{"id": "a1", "text": "abriu", "isCorrect": true}, {"id": "a2", "text": "fechou", "isCorrect": false}, {"id": "a3", "text": "trancou", "isCorrect": false}, {"id": "a4", "text": "quebrou", "isCorrect": false}]', 'easy', 'portuguese');
