-- Seed Spanish questions
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'regular', 'ar', 'Yo ______ español todos los días.', 'I speak Spanish every day.', '[{"id": "a1", "text": "hablo", "isCorrect": true}, {"id": "a2", "text": "habla", "isCorrect": false}, {"id": "a3", "text": "hablamos", "isCorrect": false}, {"id": "a4", "text": "hablan", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'regular', 'er', 'Tú ______ mucho en el restaurante.', 'You eat a lot at the restaurant.', '[{"id": "a1", "text": "comes", "isCorrect": true}, {"id": "a2", "text": "come", "isCorrect": false}, {"id": "a3", "text": "comemos", "isCorrect": false}, {"id": "a4", "text": "comen", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'regular', 'ir', 'Él ______ en Madrid con su familia.', 'He lives in Madrid with his family.', '[{"id": "a1", "text": "vive", "isCorrect": true}, {"id": "a2", "text": "vivo", "isCorrect": false}, {"id": "a3", "text": "vivimos", "isCorrect": false}, {"id": "a4", "text": "viven", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'irregular', 'er', 'Ella ______ profesora de música.', 'She is a music teacher.', '[{"id": "a1", "text": "es", "isCorrect": true}, {"id": "a2", "text": "está", "isCorrect": false}, {"id": "a3", "text": "soy", "isCorrect": false}, {"id": "a4", "text": "son", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'irregular', 'ar', 'Nosotros ______ en casa hoy.', 'We are at home today.', '[{"id": "a1", "text": "estamos", "isCorrect": true}, {"id": "a2", "text": "somos", "isCorrect": false}, {"id": "a3", "text": "estáis", "isCorrect": false}, {"id": "a4", "text": "están", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'irregular', 'ir', 'Ellos ______ al mercado cada semana.', 'They go to the market every week.', '[{"id": "a1", "text": "van", "isCorrect": true}, {"id": "a2", "text": "voy", "isCorrect": false}, {"id": "a3", "text": "va", "isCorrect": false}, {"id": "a4", "text": "vamos", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'irregular', 'er', 'Yo ______ mucha hambre ahora.', 'I am very hungry now.', '[{"id": "a1", "text": "tengo", "isCorrect": true}, {"id": "a2", "text": "tiene", "isCorrect": false}, {"id": "a3", "text": "tenemos", "isCorrect": false}, {"id": "a4", "text": "tienes", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente', 'irregular', 'er', '¿Qué ______ tú por las noches?', 'What do you do in the evenings?', '[{"id": "a1", "text": "haces", "isCorrect": true}, {"id": "a2", "text": "hace", "isCorrect": false}, {"id": "a3", "text": "hago", "isCorrect": false}, {"id": "a4", "text": "hacen", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-indefinido', 'regular', 'ar', 'Yo ______ con él ayer por teléfono.', 'I spoke with him yesterday on the phone.', '[{"id": "a1", "text": "hablé", "isCorrect": true}, {"id": "a2", "text": "habló", "isCorrect": false}, {"id": "a3", "text": "hablaba", "isCorrect": false}, {"id": "a4", "text": "hablaré", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-indefinido', 'regular', 'er', 'Ellos ______ pizza en la fiesta.', 'They ate pizza at the party.', '[{"id": "a1", "text": "comieron", "isCorrect": true}, {"id": "a2", "text": "comían", "isCorrect": false}, {"id": "a3", "text": "comerán", "isCorrect": false}, {"id": "a4", "text": "comieron", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-indefinido', 'irregular', 'ir', 'Nosotros ______ al cine el viernes.', 'We went to the cinema on Friday.', '[{"id": "a1", "text": "fuimos", "isCorrect": true}, {"id": "a2", "text": "íbamos", "isCorrect": false}, {"id": "a3", "text": "iremos", "isCorrect": false}, {"id": "a4", "text": "vamos", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-indefinido', 'irregular', 'er', 'Eso ______ un gran error.', 'That was a big mistake.', '[{"id": "a1", "text": "fue", "isCorrect": true}, {"id": "a2", "text": "era", "isCorrect": false}, {"id": "a3", "text": "será", "isCorrect": false}, {"id": "a4", "text": "es", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-indefinido', 'irregular', 'er', 'Ella ______ la verdad al final.', 'She told the truth in the end.', '[{"id": "a1", "text": "dijo", "isCorrect": true}, {"id": "a2", "text": "dice", "isCorrect": false}, {"id": "a3", "text": "decía", "isCorrect": false}, {"id": "a4", "text": "dirá", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-indefinido', 'irregular', 'er', 'Yo ______ en París el año pasado.', 'I was in Paris last year.', '[{"id": "a1", "text": "estuve", "isCorrect": true}, {"id": "a2", "text": "estaba", "isCorrect": false}, {"id": "a3", "text": "estaré", "isCorrect": false}, {"id": "a4", "text": "estoy", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-imperfecto', 'regular', 'ar', 'Cuando era niño, yo ______ mucho.', 'When I was a child, I used to talk a lot.', '[{"id": "a1", "text": "hablaba", "isCorrect": true}, {"id": "a2", "text": "hablé", "isCorrect": false}, {"id": "a3", "text": "hablaré", "isCorrect": false}, {"id": "a4", "text": "hablaría", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-imperfecto', 'irregular', 'er', 'Ella ______ muchos amigos de pequeña.', 'She used to have many friends as a child.', '[{"id": "a1", "text": "tenía", "isCorrect": true}, {"id": "a2", "text": "tuvo", "isCorrect": false}, {"id": "a3", "text": "tendrá", "isCorrect": false}, {"id": "a4", "text": "tiene", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-imperfecto', 'regular', 'ir', 'Ellos ______ en Barcelona antes.', 'They used to live in Barcelona before.', '[{"id": "a1", "text": "vivían", "isCorrect": true}, {"id": "a2", "text": "vivieron", "isCorrect": false}, {"id": "a3", "text": "vivirán", "isCorrect": false}, {"id": "a4", "text": "viven", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-imperfecto', 'irregular', 'er', 'El tiempo ______ muy bueno ese verano.', 'The weather was very good that summer.', '[{"id": "a1", "text": "era", "isCorrect": true}, {"id": "a2", "text": "fue", "isCorrect": false}, {"id": "a3", "text": "será", "isCorrect": false}, {"id": "a4", "text": "es", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro', 'regular', 'ar', 'Yo ______ con el director mañana.', 'I will speak with the director tomorrow.', '[{"id": "a1", "text": "hablaré", "isCorrect": true}, {"id": "a2", "text": "hablo", "isCorrect": false}, {"id": "a3", "text": "hablé", "isCorrect": false}, {"id": "a4", "text": "hablaba", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro', 'irregular', 'er', 'Todo ______ mejor con el tiempo.', 'Everything will be better with time.', '[{"id": "a1", "text": "será", "isCorrect": true}, {"id": "a2", "text": "es", "isCorrect": false}, {"id": "a3", "text": "era", "isCorrect": false}, {"id": "a4", "text": "fue", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro', 'irregular', 'er', 'Nosotros ______ tiempo para descansar.', 'We will have time to rest.', '[{"id": "a1", "text": "tendremos", "isCorrect": true}, {"id": "a2", "text": "tenemos", "isCorrect": false}, {"id": "a3", "text": "teníamos", "isCorrect": false}, {"id": "a4", "text": "tuvimos", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro', 'irregular', 'ir', 'Ellos ______ a la playa el próximo verano.', 'They will go to the beach next summer.', '[{"id": "a1", "text": "irán", "isCorrect": true}, {"id": "a2", "text": "van", "isCorrect": false}, {"id": "a3", "text": "fueron", "isCorrect": false}, {"id": "a4", "text": "iban", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('futuro', 'irregular', 'er', 'Ella ______ la verdad algún día.', 'She will know the truth someday.', '[{"id": "a1", "text": "sabrá", "isCorrect": true}, {"id": "a2", "text": "sabe", "isCorrect": false}, {"id": "a3", "text": "sabía", "isCorrect": false}, {"id": "a4", "text": "supo", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('condicional', 'regular', 'ar', 'Yo ______ más si tuviera tiempo.', 'I would talk more if I had time.', '[{"id": "a1", "text": "hablaría", "isCorrect": true}, {"id": "a2", "text": "hablaré", "isCorrect": false}, {"id": "a3", "text": "hablo", "isCorrect": false}, {"id": "a4", "text": "hablé", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('condicional', 'regular', 'er', '¿Tú ______ esa comida tan picante?', 'Would you eat such spicy food?', '[{"id": "a1", "text": "comerías", "isCorrect": true}, {"id": "a2", "text": "comerás", "isCorrect": false}, {"id": "a3", "text": "comes", "isCorrect": false}, {"id": "a4", "text": "comiste", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('condicional', 'irregular', 'er', 'Él ______ más paciencia en esa situación.', 'He would have more patience in that situation.', '[{"id": "a1", "text": "tendría", "isCorrect": true}, {"id": "a2", "text": "tendrá", "isCorrect": false}, {"id": "a3", "text": "tiene", "isCorrect": false}, {"id": "a4", "text": "tuvo", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('condicional', 'irregular', 'er', 'Nosotros ______ lo mismo en tu lugar.', 'We would do the same in your place.', '[{"id": "a1", "text": "haríamos", "isCorrect": true}, {"id": "a2", "text": "haremos", "isCorrect": false}, {"id": "a3", "text": "hacemos", "isCorrect": false}, {"id": "a4", "text": "hicimos", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente-progresivo', 'regular', 'ar', 'Yo ______ con mi jefe ahora mismo.', 'I am speaking with my boss right now.', '[{"id": "a1", "text": "estoy hablando", "isCorrect": true}, {"id": "a2", "text": "hablo", "isCorrect": false}, {"id": "a3", "text": "hablaré", "isCorrect": false}, {"id": "a4", "text": "estaba hablando", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente-progresivo', 'regular', 'er', 'Ella ______ la cena en este momento.', 'She is eating dinner at this moment.', '[{"id": "a1", "text": "está comiendo", "isCorrect": true}, {"id": "a2", "text": "come", "isCorrect": false}, {"id": "a3", "text": "comió", "isCorrect": false}, {"id": "a4", "text": "estaba comiendo", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente-progresivo', 'regular', 'ir', 'Nosotros ______ el momento presente.', 'We are living the present moment.', '[{"id": "a1", "text": "estamos viviendo", "isCorrect": true}, {"id": "a2", "text": "vivimos", "isCorrect": false}, {"id": "a3", "text": "viviremos", "isCorrect": false}, {"id": "a4", "text": "vivíamos", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('presente-progresivo', 'irregular', 'er', 'Ellos ______ un nuevo proyecto.', 'They are having a new project.', '[{"id": "a1", "text": "están teniendo", "isCorrect": true}, {"id": "a2", "text": "tienen", "isCorrect": false}, {"id": "a3", "text": "tendrán", "isCorrect": false}, {"id": "a4", "text": "tenían", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfecto-compuesto', 'irregular', 'er', 'Yo ______ los deberes esta tarde.', 'I have done the homework this afternoon.', '[{"id": "a1", "text": "he hecho", "isCorrect": true}, {"id": "a2", "text": "hago", "isCorrect": false}, {"id": "a3", "text": "hice", "isCorrect": false}, {"id": "a4", "text": "haré", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfecto-compuesto', 'regular', 'ar', 'Ellos ______ con nosotros esta mañana.', 'They have spoken with us this morning.', '[{"id": "a1", "text": "han hablado", "isCorrect": true}, {"id": "a2", "text": "hablaron", "isCorrect": false}, {"id": "a3", "text": "hablarán", "isCorrect": false}, {"id": "a4", "text": "hablan", "isCorrect": false}]', 'easy', 'spanish');
INSERT INTO questions (tense, regularity, verb_type, text, translation, answers, difficulty, language)
VALUES ('preterito-perfecto-compuesto', 'irregular', 'ir', 'Ella ______ a Japón este año.', 'She has gone to Japan this year.', '[{"id": "a1", "text": "ha ido", "isCorrect": true}, {"id": "a2", "text": "fue", "isCorrect": false}, {"id": "a3", "text": "irá", "isCorrect": false}, {"id": "a4", "text": "va", "isCorrect": false}]', 'easy', 'spanish');
